import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  bg-[#FFFFFF] w-full px-5 bg-[#F2F4F7]]`}>
        <div className="relative ">
          <Header/>
        </div>
        {children}
      </body>
    </html>
  );
}
